/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

/*
 * For Table Alumno
 */
public class Alumno implements java.io.Serializable, Cloneable {
    private AlumnoKey _key = new AlumnoKey();

    /* idAlumno, PK */
    protected int idalumno;

    /* nombre */
    protected String nombre;

    /* paterno */
    protected String paterno;

    /* materno */
    protected String materno;

    /* boleta */
    protected String boleta;

    /* idEscuela */
    protected int idescuela;

    /* idCategoria */
    protected int idcategoria;

    /* Return the key object. */
    public AlumnoKey getKeyObject() {
        return _key;
    }

    /* idAlumno, PK */
    public int getIdalumno() {
        return idalumno;
    }

    /* idAlumno, PK */
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
        _key.setIdalumno(idalumno);
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* paterno */
    public String getPaterno() {
        return paterno;
    }

    /* paterno */
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    /* materno */
    public String getMaterno() {
        return materno;
    }

    /* materno */
    public void setMaterno(String materno) {
        this.materno = materno;
    }

    /* boleta */
    public String getBoleta() {
        return boleta;
    }

    /* boleta */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }

    /* idEscuela */
    public int getIdescuela() {
        return idescuela;
    }

    /* idEscuela */
    public void setIdescuela(int idescuela) {
        this.idescuela = idescuela;
    }

    /* idCategoria */
    public int getIdcategoria() {
        return idcategoria;
    }

    /* idCategoria */
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Alumno))
            return false;

        Alumno bean = (Alumno) obj;

        if (this.idalumno != bean.idalumno)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.paterno == null) {
            if (bean.paterno != null)
                return false;
        }
        else if (!this.paterno.equals(bean.paterno)) 
            return false;

        if (this.materno == null) {
            if (bean.materno != null)
                return false;
        }
        else if (!this.materno.equals(bean.materno)) 
            return false;

        if (this.boleta == null) {
            if (bean.boleta != null)
                return false;
        }
        else if (!this.boleta.equals(bean.boleta)) 
            return false;

        if (this.idescuela != bean.idescuela)
            return false;

        if (this.idcategoria != bean.idcategoria)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Alumno bean = new Alumno();
        bean.idalumno = this.idalumno;
        bean.nombre = this.nombre;
        bean.paterno = this.paterno;
        bean.materno = this.materno;
        bean.boleta = this.boleta;
        bean.idescuela = this.idescuela;
        bean.idcategoria = this.idcategoria;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idalumno").append(" = ").append(idalumno).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("paterno").append(" = ").append(paterno).append("]").append(sep);
        sb.append("[").append("materno").append(" = ").append(materno).append("]").append(sep);
        sb.append("[").append("boleta").append(" = ").append(boleta).append("]").append(sep);
        sb.append("[").append("idescuela").append(" = ").append(idescuela).append("]").append(sep);
        sb.append("[").append("idcategoria").append(" = ").append(idcategoria).append("]").append(sep);
        return sb.toString();
    }
}