/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

/*
 * For Table Categoria
 */
public class Categoria implements java.io.Serializable, Cloneable {
    private CategoriaKey _key = new CategoriaKey();

    /* idCategoria, PK */
    protected int idcategoria;

    /* nombre */
    protected String nombre;

    /* rango */
    protected String rango;

    /* Return the key object. */
    public CategoriaKey getKeyObject() {
        return _key;
    }

    /* idCategoria, PK */
    public int getIdcategoria() {
        return idcategoria;
    }

    /* idCategoria, PK */
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
        _key.setIdcategoria(idcategoria);
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* rango */
    public String getRango() {
        return rango;
    }

    /* rango */
    public void setRango(String rango) {
        this.rango = rango;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Categoria))
            return false;

        Categoria bean = (Categoria) obj;

        if (this.idcategoria != bean.idcategoria)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        if (this.rango == null) {
            if (bean.rango != null)
                return false;
        }
        else if (!this.rango.equals(bean.rango)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Categoria bean = new Categoria();
        bean.idcategoria = this.idcategoria;
        bean.nombre = this.nombre;
        bean.rango = this.rango;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcategoria").append(" = ").append(idcategoria).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        sb.append("[").append("rango").append(" = ").append(rango).append("]").append(sep);
        return sb.toString();
    }
}