/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

/*
 * For Table Competidor
 */
public class Competidor implements java.io.Serializable, Cloneable {
    private CompetidorKey _key = new CompetidorKey();

    /* idCompetidor, PK */
    protected int idcompetidor;

    /* idAlumno */
    protected int idalumno;

    /* Return the key object. */
    public CompetidorKey getKeyObject() {
        return _key;
    }

    /* idCompetidor, PK */
    public int getIdcompetidor() {
        return idcompetidor;
    }

    /* idCompetidor, PK */
    public void setIdcompetidor(int idcompetidor) {
        this.idcompetidor = idcompetidor;
        _key.setIdcompetidor(idcompetidor);
    }

    /* idAlumno */
    public int getIdalumno() {
        return idalumno;
    }

    /* idAlumno */
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Competidor))
            return false;

        Competidor bean = (Competidor) obj;

        if (this.idcompetidor != bean.idcompetidor)
            return false;

        if (this.idalumno != bean.idalumno)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Competidor bean = new Competidor();
        bean.idcompetidor = this.idcompetidor;
        bean.idalumno = this.idalumno;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcompetidor").append(" = ").append(idcompetidor).append("]").append(sep);
        sb.append("[").append("idalumno").append(" = ").append(idalumno).append("]").append(sep);
        return sb.toString();
    }
}