/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

public class CompetidorKey implements java.io.Serializable, Cloneable {
    /* idCompetidor */
    protected int idcompetidor;

    /* idCompetidor */
    public int getIdcompetidor() {
        return idcompetidor;
    }

    /* idCompetidor */
    public void setIdcompetidor(int idcompetidor) {
        this.idcompetidor = idcompetidor;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcompetidor).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CompetidorKey))
            return false;

        CompetidorKey key = (CompetidorKey) obj;

        if (this.idcompetidor != key.idcompetidor)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CompetidorKey key = new CompetidorKey();
        key.idcompetidor = this.idcompetidor;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcompetidor").append(" = ").append(idcompetidor).append("]");
        return sb.toString();
    }
}