/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

/*
 * For Table Escuela
 */
public class Escuela implements java.io.Serializable, Cloneable {
    private EscuelaKey _key = new EscuelaKey();

    /* idEscuela, PK */
    protected int idescuela;

    /* nombre */
    protected String nombre;

    /* Return the key object. */
    public EscuelaKey getKeyObject() {
        return _key;
    }

    /* idEscuela, PK */
    public int getIdescuela() {
        return idescuela;
    }

    /* idEscuela, PK */
    public void setIdescuela(int idescuela) {
        this.idescuela = idescuela;
        _key.setIdescuela(idescuela);
    }

    /* nombre */
    public String getNombre() {
        return nombre;
    }

    /* nombre */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Escuela))
            return false;

        Escuela bean = (Escuela) obj;

        if (this.idescuela != bean.idescuela)
            return false;

        if (this.nombre == null) {
            if (bean.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(bean.nombre)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Escuela bean = new Escuela();
        bean.idescuela = this.idescuela;
        bean.nombre = this.nombre;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idescuela").append(" = ").append(idescuela).append("]").append(sep);
        sb.append("[").append("nombre").append(" = ").append(nombre).append("]").append(sep);
        return sb.toString();
    }
}