/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

/*
 * For Table Pelea
 */
public class Pelea implements java.io.Serializable, Cloneable {
    private PeleaKey _key = new PeleaKey();

    /* idPelea, PK */
    protected int idpelea;

    /* idCompetidorA */
    protected int idcompetidora;

    /* idCompetidorB */
    protected int idcompetidorb;

    /* Return the key object. */
    public PeleaKey getKeyObject() {
        return _key;
    }

    /* idPelea, PK */
    public int getIdpelea() {
        return idpelea;
    }

    /* idPelea, PK */
    public void setIdpelea(int idpelea) {
        this.idpelea = idpelea;
        _key.setIdpelea(idpelea);
    }

    /* idCompetidorA */
    public int getIdcompetidora() {
        return idcompetidora;
    }

    /* idCompetidorA */
    public void setIdcompetidora(int idcompetidora) {
        this.idcompetidora = idcompetidora;
    }

    /* idCompetidorB */
    public int getIdcompetidorb() {
        return idcompetidorb;
    }

    /* idCompetidorB */
    public void setIdcompetidorb(int idcompetidorb) {
        this.idcompetidorb = idcompetidorb;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Pelea))
            return false;

        Pelea bean = (Pelea) obj;

        if (this.idpelea != bean.idpelea)
            return false;

        if (this.idcompetidora != bean.idcompetidora)
            return false;

        if (this.idcompetidorb != bean.idcompetidorb)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Pelea bean = new Pelea();
        bean.idpelea = this.idpelea;
        bean.idcompetidora = this.idcompetidora;
        bean.idcompetidorb = this.idcompetidorb;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idpelea").append(" = ").append(idpelea).append("]").append(sep);
        sb.append("[").append("idcompetidora").append(" = ").append(idcompetidora).append("]").append(sep);
        sb.append("[").append("idcompetidorb").append(" = ").append(idcompetidorb).append("]").append(sep);
        return sb.toString();
    }
}