/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.squirrel;

public class PeleaKey implements java.io.Serializable, Cloneable {
    /* idPelea */
    protected int idpelea;

    /* idPelea */
    public int getIdpelea() {
        return idpelea;
    }

    /* idPelea */
    public void setIdpelea(int idpelea) {
        this.idpelea = idpelea;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idpelea).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PeleaKey))
            return false;

        PeleaKey key = (PeleaKey) obj;

        if (this.idpelea != key.idpelea)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PeleaKey key = new PeleaKey();
        key.idpelea = this.idpelea;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idpelea").append(" = ").append(idpelea).append("]");
        return sb.toString();
    }
}