/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu Apr 07 13:42:43 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.mx.ipn.app.modelo.daoimpl;

import com.mx.ipn.app.modelo.squirrel.Alumno;
import com.mx.ipn.app.modelo.squirrel.AlumnoKey;
import com.mx.ipn.app.modelo.squirrel.dao.AlumnoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;


/**
 * This class provides methods to populate DB Table of Alumno
 */
public class AlumnoDAOImpl implements AlumnoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Alumno ("
        + "idAlumno, nombre, paterno, materno, boleta, idEscuela, idCategoria"
        + ") VALUES (?, ?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idAlumno, nombre, paterno, materno, boleta, idEscuela, idCategoria "
        + "FROM Alumno WHERE "
        + "idAlumno = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Alumno SET "
        + "nombre = ?, paterno = ?, materno = ?, boleta = ?, idEscuela = ?, idCategoria = ? "
        + "WHERE "
        + "idAlumno = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Alumno WHERE "
        + "idAlumno = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Alumno bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdalumno());
            ps.setString(2, bean.getNombre());
            ps.setString(3, bean.getPaterno());
            ps.setString(4, bean.getMaterno());
            ps.setString(5, bean.getBoleta());
            ps.setInt(6, bean.getIdescuela());
            ps.setInt(7, bean.getIdcategoria());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Alumno load(AlumnoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdalumno());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Alumno) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Alumno bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombre());
            ps.setString(2, bean.getPaterno());
            ps.setString(3, bean.getMaterno());
            ps.setString(4, bean.getBoleta());
            ps.setInt(5, bean.getIdescuela());
            ps.setInt(6, bean.getIdcategoria());
            ps.setInt(7, bean.getIdalumno());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(AlumnoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdalumno());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    public List<Alumno> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Alumno>();
        while (rs.next()) {
            Alumno bean = new Alumno();
            bean.setIdalumno(rs.getInt("idAlumno"));
            bean.setNombre(rs.getString("nombre"));
            bean.setPaterno(rs.getString("paterno"));
            bean.setMaterno(rs.getString("materno"));
            bean.setBoleta(rs.getString("boleta"));
            bean.setIdescuela(rs.getInt("idEscuela"));
            bean.setIdcategoria(rs.getInt("idCategoria"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}